### ISSUE TITLE
Node modules prec

### ISSUE THREAD

**Issue by selrond** [seki98/ITUpaint#1]
Kamo node_modules priecinok si daj do .gitignore, uplne zbytocne to tam mas, plus ked to budes klonovat niekde sa ti moze babrat kod...
b50f0c220d9df1a7202a64135d289e790f953d71

**Comment by seki98** [comment]
No v podstate hned jak som to pushol tak som to musel zmazat a nainstalovat znova na servery, mas pravdu, este som s tym vobec nerobil, len som potreboval narychlo rozbehnut server, ze ci to pojde jak chcem.

Ale dik za tip ;)
